### ISSUE TITLE
MissingSourceFile

### ISSUE THREAD

**Issue by mrrooijen** [grimen/validatious-on-rails#1]
I was trying to test out this interesting plugin, both as a plugin as well as a gem.

After installing the plugin and it's specified dependencies (the other two plugins, as it says in the readme) and running ./script/server I get the following output:

Michael-van-Rooijens-MacBook-Pro:test_app Michael$ script/server 
=> Booting Mongrel
=> Rails 2.3.4 application starting on http://0.0.0.0:3000
/Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- /Users/Michael/Desktop/test_app/vendor/plugins/validatious-on-rails/lib/validatious (MissingSourceFile)
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in`require'
    from /Library/Ruby/Gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:156:in `require'
    from /Library/Ruby/Gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:521:in`new_constants_in'
    from /Library/Ruby/Gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:156:in `require'
    from /Users/Michael/Desktop/test_app/vendor/plugins/validatious-on-rails/rails/init.rb:2:in`evaluate_init_rb'
    from /Library/Ruby/Gems/1.8/gems/rails-2.3.4/lib/rails/plugin.rb:158:in `evaluate_init_rb'
    from /Library/Ruby/Gems/1.8/gems/activesupport-2.3.4/lib/active_support/core_ext/kernel/reporting.rb:11:in`silence_warnings'
    from /Library/Ruby/Gems/1.8/gems/rails-2.3.4/lib/rails/plugin.rb:154:in `evaluate_init_rb'
    from /Library/Ruby/Gems/1.8/gems/rails-2.3.4/lib/rails/plugin.rb:48:in`load'
    from /Library/Ruby/Gems/1.8/gems/rails-2.3.4/lib/rails/plugin/loader.rb:38:in `load_plugins'
    from /Library/Ruby/Gems/1.8/gems/rails-2.3.4/lib/rails/plugin/loader.rb:37:in`each'
    from /Library/Ruby/Gems/1.8/gems/rails-2.3.4/lib/rails/plugin/loader.rb:37:in `load_plugins'
    from /Library/Ruby/Gems/1.8/gems/rails-2.3.4/lib/initializer.rb:369:in`load_plugins'
    from /Library/Ruby/Gems/1.8/gems/rails-2.3.4/lib/initializer.rb:165:in `process'
    from /Library/Ruby/Gems/1.8/gems/rails-2.3.4/lib/initializer.rb:113:in`send'
    from /Library/Ruby/Gems/1.8/gems/rails-2.3.4/lib/initializer.rb:113:in `run'
    from /Users/Michael/Desktop/test_app/config/environment.rb:9
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `require'
    from /Library/Ruby/Gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:156:in`require'
    from /Library/Ruby/Gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:521:in `new_constants_in'
    from /Library/Ruby/Gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:156:in`require'
    from /Library/Ruby/Gems/1.8/gems/rails-2.3.4/lib/commands/server.rb:84
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in`require'
    from script/server:3
Michael-van-Rooijens-MacBook-Pro:test_app Michael$ 
Michael-van-Rooijens-MacBook-Pro:test_app Michael$ ruby -v
ruby 1.8.7 (2008-08-11 patchlevel 72) [universal-darwin10.0]
Michael-van-Rooijens-MacBook-Pro:test_app Michael$ rails -v
Rails 2.3.4
Michael-van-Rooijens-MacBook-Pro:test_app Michael$ 

Any idea what's causing this?

**Comment by grimen** [comment]
Fixed incorrect load path causing MissingSourceFile error on Rails boot. closed by 260c38c84fc43b2fb39aae2f8697ab713c581aca

**Comment by grimen** [comment]
Ouch, I was a bit too fast there with closing this. Solved this loading issue but not the next one. xP Will try to fix it now before I continue with the TODO.

**Comment by grimen** [comment]
Now it works well for me even in a live project. Let me know if u get any more problems!
