### ISSUE TITLE
Review all form helpers

### ISSUE THREAD

**Issue by grimen** [grimen/validatious-on-rails#10]
Seems like some have issues with the form helpers... Need to write tests for each helper.

**Comment by grimen** [comment]
Added tests for all form field helpers, and squashing a grouped_collection_select-bug caused by a typo. closed by 87feb4d4b0b1591a1460bd0bae24dc747fb61486

**Comment by lapluviosilla** [comment]
FYI: this modification breaks validatious-on-rails if you are using Rails 2.3.3. I use 2.3.4 so it doesn't affect me. If you take my test-app and change it back to Rails 2.3.3 you can reproduce the error.

<pre>
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/core_ext/module/aliasing.rb:33:in `alias_method': undefined method `grouped_collection_select' for module `ActionView::Helpers::FormOptionsHelper' (NameError)
</pre>

**Comment by grimen** [comment]
Yep I know why, I did that when I was very tired. =D Thanks for the "reminder"!
