### ISSUE TITLE
generator doesn't put files in the right location

### ISSUE THREAD

**Issue by FloWi** [grimen/validatious-on-rails#11]
Hi!

I've got a problem with the validatious generator.
The files' paths are not separated by a '/' but by a ' ' (space).
This means, the files are all in the root-dir of the rails-app looking like that (see my terminal output below)

Feel free to contact me, if you have questions about that issue.
- Florian
  <pre>

README   app      db       lib      public   test     vendor
Rakefile config   doc      log      script   tmp
[~/programming/rails_sites/railscasts/vet](ls): ./script/generate validatious
      create  config initializers validatious-on-rails.rb
      create  public javascripts XMLHttpRequest.js
      create  public javascripts v2.standalone.full.min.js
      create  public javascripts v2.config.js
      create  public javascripts v2.rails.js

README                                       public
Rakefile                                     public javascripts XMLHttpRequest.js
app                                          public javascripts v2.config.js
config                                       public javascripts v2.rails.js
config initializers validatious-on-rails.rb  public javascripts v2.standalone.full.min.js
db                                           script
doc                                          test
lib                                          tmp
log                                          vendor
</pre>

**Comment by grimen** [comment]
Fixed typo in the generator. closed by 8930c990b622b1f96e76b5708399795ccb716edd

**Comment by FloWi** [comment]
Thanks for the quick fix!
