### ISSUE TITLE
Syntax error in lib/validatious-on-rails/model_validations.rb

### ISSUE THREAD

**Issue by charliemaffitt** [grimen/validatious-on-rails#2]
Tried to install the plugin this morning, but when I ran script/generate validatious, I got the following error:

/vendor/plugins/validatious-on-rails/lib/validatious-on-rails/model_validations.rb:263: syntax error, unexpected ',', expecting kEND (SyntaxError)
          "ValidatiousOnRails::ModelValidations.add(<CustomValidationClass>)", :warn

I noticed you changed that file earlier today, and when I manually rolled back your change on that line, the generator worked. Looks like just a syntax issue.

**Comment by grimen** [comment]
Will look into this tonight - have to install snow leopard first. ;)

**Comment by grimen** [comment]
Fixing the syntax error mistake, and fixing a validator test issue that was a bit too lame. closed by 1c0287ba7917a5ad1f7f1730d75c5c0e5a7db130
