### ISSUE TITLE
Refresh Validations

### ISSUE THREAD

**Issue by rajington** [grimen/validatious-on-rails#20]
When I dynamically add more inputs to a form via AJAX the new inputs do not use validation. 

I inspected them and made sure they were exactly the same structurally, there is probably some javascript function I have to call to have validatious look at the newly generated inputs.

More detailed:
I have a parent model with a required name. It has_many child models with required names. If I create a form with a new parent model and 3 children model, the name validation works on all 4 name inputs (1 parent + 3 children). If I add another child dynamically via AJAX, the 5th name input does not validate.

**Comment by grimen** [comment]
It would be helpful if you could re-create this issue with a dummie-app: http://github.com/grimen/test_app

**Comment by adrianpike** [comment]
rajington, I'm not sure if you're still watching this, but something like this is what you want to include in what gets loaded:

<%= javascript_for_validatious %>

<script type="text/javascript">
var form = $('#new_event')[0];
new v2.html.Form(form);
</script>


You'll want to unload the previous form v2 form before you load up the new one - I'm using this code to load an entire new form into the DOM and validate it.

**Comment by rajington** [comment]
Thanks a lot adrianpike. I'll close this now.

**Comment by miloops** [comment]
I'm trying to do this but it doesn't load the new fields, prob because i'm not unloading the previous v2 form, how can i do this?
