### ISSUE TITLE
Stack level too deep

### ISSUE THREAD

**Issue by charliemaffitt** [grimen/validatious-on-rails#3]
Using gem version 0.3.1, Rails 2.3.4. Have installed validatious and validation_reflection plugins. Have installed most recent version of validatious-on-rails plugin from github. 

I'm still not convinced this isn't just a problem with my setup, but this is the error & server log trace for the error I am getting: 

Processing Manage::ConditionsController#edit (for 127.0.0.1 at 2009-10-06 15:41:39) [GET]
  Parameters: {"action"=>"edit", "id"=>"2", "controller"=>"manage/conditions"}
Rendering template within layouts/manage
Rendering manage/conditions/edit

ActionView::TemplateError (stack level too deep) on line #7 of app/views/manage/conditions/_form.html.erb:
4:   <h4>Condition Details</h4>
5:   <p>
6: 
7:     <%= f.text_field :name, :class => 'formfield' %>
8:  
9:   </p>
10:   <p>

```
/usr/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.1/lib/validatious-on-rails/model_validations.rb:70:in `from_active_record'
/usr/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.1/lib/validatious-on-rails/model_validations.rb:51:in `options_for'
/usr/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.1/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in `text_field_without_validation'
/usr/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.1/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in `send'
/usr/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.1/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in `text_field_with_validation'
app/views/manage/conditions/_form.html.erb:7
app/views/manage/conditions/edit.html.erb:5
app/views/manage/conditions/edit.html.erb:4
```

According to the trace in the browser, it looks like it is getting caught in a loop somewhere:

/Users/charlie/projects/spinecenter/vendor/plugins/validatious-on-rails/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in `text_field_with_validation'
/Users/charlie/projects/spinecenter/vendor/plugins/validatious-on-rails/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in`text_field_without_validation'
/Users/charlie/projects/spinecenter/vendor/plugins/validatious-on-rails/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in `send'
/Users/charlie/projects/spinecenter/vendor/plugins/validatious-on-rails/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in`text_field_with_validation'
/Users/charlie/projects/spinecenter/vendor/plugins/validatious-on-rails/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in `text_field_without_validation'
/Users/charlie/projects/spinecenter/vendor/plugins/validatious-on-rails/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in`send'
/Users/charlie/projects/spinecenter/vendor/plugins/validatious-on-rails/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in `text_field_with_validation'
/Users/charlie/projects/spinecenter/vendor/plugins/validatious-on-rails/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in`text_field_without_validation'
/Users/charlie/projects/spinecenter/vendor/plugins/validatious-on-rails/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in `send'
/Users/charlie/projects/spinecenter/vendor/plugins/validatious-on-rails/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in`text_field_with_validation'
/Users/charlie/projects/spinecenter/vendor/plugins/validatious-on-rails/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in `text_field_without_validation'
/Users/charlie/projects/spinecenter/vendor/plugins/validatious-on-rails/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in`send'
/Users/charlie/projects/spinecenter/vendor/plugins/validatious-on-rails/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in `text_field_with_validation'
/Users/charlie/projects/spinecenter/vendor/plugins/validatious-on-rails/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in`text_field_without_validation'
/Users/charlie/projects/spinecenter/vendor/plugins/validatious-on-rails/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in `send'
/Users/charlie/projects/spinecenter/vendor/plugins/validatious-on-rails/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in`text_field_with_validation'
/usr/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.1/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in `text_field_without_validation'
/usr/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.1/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in`send'
/usr/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.1/lib/validatious-on-rails/rails/action_view_helpers.rb:29:in `text_field_with_validation'
/usr/local/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_view/helpers/form_helper.rb:944:in`text_field'
/usr/local/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_view/helpers/form_helper.rb:944:in `send'
/usr/local/lib/ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_view/helpers/form_helper.rb:944:in`text_field'
/Users/charlie/projects/spinecenter/app/views/manage/conditions/edit.html.erb:14:in `_run_erb_app47views47manage47conditions47edit46html46erb'
/Users/charlie/projects/spinecenter/app/views/manage/conditions/edit.html.erb:4:in`_run_erb_app47views47manage47conditions47edit46html46erb'

**Comment by grimen** [comment]
I can't reproduce this at all I'm afraid. Use Gemcutter gem version, and uninstall all the previous versions. SOmetimes Rubygems confuse things.

**Comment by grimen** [comment]
Can't reproduce, feel free to re-open if it's still an issue.
