### ISSUE TITLE
suggestion for easy xhtml conformity at javascript_for_validatious

### ISSUE THREAD

**Issue by volontarian** [grimen/validatious-on-rails#33]
The javascript_for_validatious should be embraced by the Rails TagHelper cdata_section, too.

This is my monkey patch at helpers.rb attached_validators ;-)

content_tag(:script, "\n //" + cdata_section("\n " + @content_for_validatious + " \n//") + "\n",
          :type => 'text/javascript', :id => 'custom_validators')

Than the w3c validator attents xhtml conform markup again.

Sorry, I'm not able to contribute over github yet :-(

**Comment by volontarian** [comment]
Thought my version is up to data and don't saw the niftier solution by a javascript_tag.

No issue anymore.

**Comment by grimen** [comment]
OK, closing.
