### ISSUE TITLE
`uninitialized constant`

### ISSUE THREAD

**Issue by lapluviosilla** [grimen/validatious-on-rails#7]
I get an "uninitialized constant" error on many different pages. It looks like validatious-on-rails is trying to lookup validations on all my forms including those that don't have real models. For example, I use searchlogic as my search engine and I have a search form "for" a "search" instance variable, but it's only an internal variable used by searchlogic, not a real model. I can't figure out a way to tell validatious-on-rails to ignore those forms. In this case the error it gives is "uninitialized constant Search". This same error happens on a lot of pages.

Search form:
    - form_for @beneficiaries_search, :url => beneficiaries_path do |f|
      = f.text_field :full_name_like
      = f.submit t 'homepage.search'

Stack trace:

<pre>
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/activesupport/lib/active_support/dependencies.rb:443:in `load_missing_constant'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/activesupport/lib/active_support/dependencies.rb:80:in `const_missing'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/activesupport/lib/active_support/dependencies.rb:92:in `const_missing'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/activesupport/lib/active_support/inflector.rb:361:in `constantize'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/activesupport/lib/active_support/inflector.rb:360:in `each'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/activesupport/lib/active_support/inflector.rb:360:in `constantize'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/activesupport/lib/active_support/core_ext/string/inflections.rb:162:in `constantize'
/opt/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.5/lib/validatious-on-rails/model_validations.rb:69:in `from_active_record'
/opt/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.5/lib/validatious-on-rails/model_validations.rb:43:in `options_for'
/opt/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.5/lib/validatious-on-rails/helpers.rb:5:in `attach_validator_for'
/opt/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.5/lib/validatious-on-rails/rails/action_view_helpers.rb:21:in `text_field_with_validation'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/actionpack/lib/action_view/helpers/form_helper.rb:944:in `text_field'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/actionpack/lib/action_view/helpers/form_helper.rb:944:in `send'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/actionpack/lib/action_view/helpers/form_helper.rb:944:in `text_field'
/Users/paul/Documents/Projects/msvngit/rails/app/views/home/index.html.haml:12:in `_run_haml_app47views47home47index46html46haml'
/Users/paul/Documents/Projects/msvngit/rails/app/views/home/index.html.haml:11:in `_run_haml_app47views47home47index46html46haml'
</pre>

**Comment by lapluviosilla** [comment]
Just an idea:

Maybe there needs to be way to either exclude a form or specify what the real model name is for that form in case auto detection is not possible. For example, I have a new event form on another page that for many reasons has to be loaded as a hash instead of loading the model into an instance variable like in most of the cases. The fields and everything else carry the exact same name so validation should be possible if this were to be implemented.

In the case of this beneficiaries_search form since there is no concrete model for it by default you could just disable checking validations, but if the user specifies a reference model then use that instead.

**Comment by grimen** [comment]
Ouch, I tagged this one incorrect. Status of this one should be same as the Authlogic:Session::Base ticket. If you can come up with a smart solution on this it would be nice, but I'm putting lower priority on this one. Solid ActiveRecord::Base-support is most important right now.

**Comment by lapluviosilla** [comment]
Agreed, you don't have to necessarily support the other scenarios yet, but my point is that the site just dies which makes the gem unusable. If anything it should at least fallback to doing nothing. I found the line where it breaks, so I'm going to fork and try and figure out if I can get it to fall back.

It breaks at #72 of lib/validatious-on-rails/model_validations.rb `klass = object_or_class.to_s.classify.constantize`

**Comment by grimen** [comment]
OK, then I see - sorry, a bit sleepy. -_- Would be neat if you fix that before me, sounds like a serious issue then.

**Comment by grimen** [comment]
Fixed the "uninitialized constant"-issue that arise for non-concrete models. closed by a2043b2e5ffbfc5ea755ceae122da5570dfd8bb0

**Comment by lapluviosilla** [comment]
I think you reintroduced this bug in http://github.com/grimen/validatious-on-rails/commit/ada98f936507569bc11689f50efac5676772d70a

**Comment by grimen** [comment]
OK, try now.
