### ISSUE TITLE
`wrong constant name Account[ownerAttributes]'

### ISSUE THREAD

**Issue by lapluviosilla** [grimen/validatious-on-rails#8]
validatious-on-rails is complaining about my nested formtastic form apparently. I get this error when the nested form is for an actual association (owner) on the main resource (account) and I get an 'uninitialized constant' error on the pages where the nested form is for some variable that is not an actual model.

Sign Up form:
    - semantic_form_for @account do |f|
      = f.inputs :login, :password, :password_confirmation
      = f.inputs :first_name, :last_name, :email, :for => :owner
      = f.buttons

Stack trace:

<pre>
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/activesupport/lib/active_support/inflector.rb:361:in `const_defined?'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/activesupport/lib/active_support/inflector.rb:361:in `constantize'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/activesupport/lib/active_support/inflector.rb:360:in `each'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/activesupport/lib/active_support/inflector.rb:360:in `constantize'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/activesupport/lib/active_support/core_ext/string/inflections.rb:162:in `constantize'
/opt/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.5/lib/validatious-on-rails/model_validations.rb:69:in `from_active_record'
/opt/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.5/lib/validatious-on-rails/model_validations.rb:43:in `options_for'
/opt/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.5/lib/validatious-on-rails/helpers.rb:5:in `attach_validator_for'
/opt/local/lib/ruby/gems/1.8/gems/validatious-on-rails-0.3.5/lib/validatious-on-rails/rails/action_view_helpers.rb:21:in `text_field_with_validation'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/actionpack/lib/action_view/helpers/form_helper.rb:944:in `text_field'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/actionpack/lib/action_view/helpers/form_helper.rb:944:in `send'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/actionpack/lib/action_view/helpers/form_helper.rb:944:in `text_field'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:497:in `send'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:497:in `input_simple'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:946:in `inline_input_for'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:108:in `send'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:108:in `input'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:107:in `map'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:107:in `input'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:256:in `inputs'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:256:in `map'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:256:in `inputs'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:413:in `inputs_for_nested_attributes'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/actionpack/lib/action_view/helpers/form_helper.rb:490:in `fields_for'
/Users/paul/Documents/Projects/msvngit/rails/vendor/gems/searchlogic-2.3.5/lib/searchlogic/rails_helpers.rb:72:in `fields_for'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/actionpack/lib/action_view/helpers/form_helper.rb:1033:in `fields_for_nested_model'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/actionpack/lib/action_view/helpers/form_helper.rb:1027:in `fields_for_with_nested_attributes'
/Users/paul/Documents/Projects/msvngit/rails/vendor/rails/actionpack/lib/action_view/helpers/form_helper.rb:964:in `fields_for'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:326:in `semantic_fields_for'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:417:in `inputs_for_nested_attributes'
/opt/local/lib/ruby/gems/1.8/gems/formtastic-0.2.5/lib/formtastic.rb:246:in `inputs'
/Users/paul/Documents/Projects/msvngit/rails/app/views/accounts/new.html.haml:5:in `_run_haml_app47views47accounts47new46html46haml'
/Users/paul/Documents/Projects/msvngit/rails/app/views/accounts/new.html.haml:3:in `_run_haml_app47views47accounts47new46html46haml'
/Users/paul/Documents/Projects/msvngit/rails/app/controllers/accounts_controller.rb:8:in `new'
</pre>

**Comment by grimen** [comment]
See issue #5.
